M48
; DRILL file KiCad 10.0.6 date 2026-10-06T21:17:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T21:17:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X122.84Y-112.0
X133.0Y-112.0
X167.84Y-112.0
X178.0Y-112.0
T2
X127.92Y-112.0
X172.92Y-112.0
M30
